---
packages:
  # This will be installed on all platforms
  "*": ["git", "curl", "bat", "gcc"]
  # Parsed from "id" in /etc/os-release -- Appended to *
  debian: []
  ubuntu: []

clone:
  # Relative to $HOME
  ~/.config/nvim:
    url: "https://github.com/aarondill/LazyVim.git"
    args: ["--filter=tree:0"]
