#!/usr/bin/env bash

# ~/.bashrc.d/03_secrets
#
# Stores variables and functions which contain
# secret information which should be encrypted
# This stuff *should* be stored in `bw`, but
# it seems to be slightly broken.
#

# Release-it Github Key
export RELEASE_IT_GITHUB_KEY='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'
# Bitwarden session key
export BW_SESSION=''
# freedesktop gitlab token
export FREEDESKTOP_GITLAB_TOKEN='glpat-NKxGrovt_RvDZ3ViTsXg'
